Credentials extraction from specified path or from AWS CLI
QuantStack/jupyter-drives pull request #14
Opened 2024-01-14 15:45 UTC by DenisaCG

Added credentials extraction directly from where they are stored for `AWS` CLI users, namely in `~/.aws/credentials`, as well as from a user specified path to a file which contains their credentials.

Now, the extension supports:
-  setting credentials in `jupyter_notebook_config.py`
- direct extraction of credentials for the `AWS` CLI tool users
- extracting credentials from a user specific file.

While the `AWS` CLI tool credentials extraction only benefits `S3` users, the other two options keep the architecture open for other kind of drives as well.

2024-01-17 14:08 UTC, trungleduc requested changes

2024-01-18 13:53 UTC, DenisaCG commented on jupyter_drives/base.py
> +        help="Custom path of file where credentials are located. Extension automatically checks jupyter_notebook_config.py or directly in ~/.aws/credentials for AWS CLI users."
Users would have to specify the custom file path inside `jupyter_notebook_config.py`, for now. It would also be useful to consider implementing another way where users can specify the file path of their credentials without having to make a configuration file.

And what is mentioned inside the `help` section is that credentials are automatically searched for in `jupyter_notebook_config.py` or the specific location for `AWS` CLI users. 

 I'm not sure if this answers your question?

2024-01-18 18:33 UTC, trungleduc commented on jupyter_drives/base.py
> +        help="Custom path of file where credentials are located. Extension automatically checks jupyter_notebook_config.py or directly in ~/.aws/credentials for AWS CLI users."
Thanks for the explanation.

2024-03-12 10:47 UTC, DenisaCG commented
Thanks for your review @trungleduc!

As we need this functionality for the current version, I will merge this PR and later open a new one where I will make the suggested improvements.

2024-03-12 10:47 UTC, merged