WIP Listing all available drives
QuantStack/jupyter-drives pull request #3
Opened 2023-10-30 17:14 UTC by DenisaCG

Created a config class `DrivesConfig`, a base API handler class `JupyterDrivesAPIHandler` and base manager class `JupyterDrivesManager`, as well as the initial logic for listing available drives.

2023-11-09 12:23 UTC, fcollonval reviewed
Thanks @DenisaCG this looks very promising

2023-11-09 12:23 UTC, fcollonval commented on jupyter_drives/handlers.py
> +        self.finish(json.dumps({"data": "Get available drives"}))
```suggestion
```

2023-11-09 12:23 UTC, fcollonval commented on jupyter_drives/handlers.py
> +class ExampleJupyterDrivesHandler(JupyterDrivesAPIHandler):
To be removed

2023-11-09 12:23 UTC, fcollonval commented on jupyter_drives/handlers.py
> +    ("get-example", ExampleJupyterDrivesHandler),
```suggestion
```

2023-11-09 12:23 UTC, fcollonval commented on jupyter_drives/managers/manager.py
> +        self._client = tornado.httpclient.AsyncHTTPClient()
On a JupyterLab issue it was pointed out that a limitation of that client is the inability to support proxy. As this is a damn important feature in corporations, I would suggest using `httpx` (as done in JupyterLab to solve that issue).

2023-11-09 12:23 UTC, fcollonval commented on jupyter_drives/managers/manager.py
> +    async def _call_provider(
We may not be as lucky as the pull requests extension about this. But let's see how it goes in the future.

2023-11-13 14:45 UTC, DenisaCG commented on jupyter_drives/managers/manager.py
> +        self._client = tornado.httpclient.AsyncHTTPClient()
Thanks for pointing this out! I pushed a new commit which switches to using `httpx`.

2023-11-20 14:27 UTC, fcollonval requested changes
Thanks @DenisaCG 

I have some minor suggestion, but it looks really great.

2023-11-20 14:27 UTC, fcollonval commented on jupyter_drives/base.py
> +        "",
Should it be `None` by default as you allow it?

2023-11-20 14:27 UTC, fcollonval commented on jupyter_drives/base.py
> +        "",
Same question

2023-11-20 14:27 UTC, fcollonval commented on jupyter_drives/base.py
> +        "",
Same question

2023-11-20 14:27 UTC, fcollonval commented on jupyter_drives/handlers.py
> +        logging.debug(error)
Let's use this extension logger to scope this message:

```suggestion
        get_logger().debug(error)
```

2023-11-20 14:27 UTC, fcollonval commented on jupyter_drives/handlers.py
> +    ("get-listDrives", ListJupyterDrives)
Let's be more RESTful:

```suggestion
    ("drives", ListJupyterDrives)
```

2023-11-20 14:27 UTC, fcollonval commented on jupyter_drives/managers/s3.py
> +                print(drive.list_containers())
You may want to send a `log.debug` message here

```suggestion
```

2023-11-20 14:27 UTC, fcollonval commented on jupyter_drives/tests/test_handlers.py
> +async def test_ListJupyterDrives(jp_fetch, set_s3_base):
Nice it will be good to add some tests for failing cases and for empty drive list.

2023-11-20 14:56 UTC, DenisaCG commented on jupyter_drives/base.py
> +        "",
Thanks for catching this!

2023-11-20 15:55 UTC, DenisaCG commented
Thanks for the review and suggestions @fcollonval!

2023-11-20 15:56 UTC, merged

2023-11-21 08:54 UTC, fcollonval reviewed
@DenisaCG I have some post mortem comment. If you could take them into account in a follow-up PR it will be great

2023-11-21 08:54 UTC, fcollonval commented on jupyter_drives/tests/test_handlers.py
> +        response = await jp_fetch("jupyter-drives", "drives")
What is the error code if the credentials are invalid? Do we get an error code like 401 that could in the future be used in the frontend to notify the user credentials are invalid?

2023-11-21 08:54 UTC, fcollonval commented on tsconfig.json
> +    // "sourceRoot": "./@jupyter/drives/src",
Let's remove that

2023-11-21 08:54 UTC, fcollonval commented on jupyter_drives/managers/s3.py
> +        # results = await self._call_s3(drives_url)
Let's remove that

2023-11-21 08:54 UTC, fcollonval commented on jupyter_drives/managers/s3.py
> +            error = "No AWS credentials provided."
We should raise an error instead

Similar to how we deal with missing credential in `_call_provider`